# Generated by Django 4.2.22 on 2025-06-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('market_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'db_table': '"betting_data"."markets"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'db_table': '"betting_data"."participants"',
                'managed': False,
            },
        ),
    ]
