# Generated by Django 4.2.22 on 2025-06-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_data', '0002_market_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('bookmaker_id', models.UUIDField(blank=True, null=True)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('back_lay', models.CharField(blank=True, choices=[('back', 'Back'), ('lay', 'Lay')], max_length=4, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Odds',
                'verbose_name_plural': 'Odds',
                'db_table': '"betting_data"."odds"',
                'managed': False,
            },
        ),
    ]
