# Generated by Django 4.2.22 on 2025-06-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_data', '0003_odds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('default_back_lay', models.CharField(choices=[('back', 'Back'), ('lay', 'Lay')], default='back', max_length=4)),
            ],
            options={
                'verbose_name': 'Bookmaker',
                'verbose_name_plural': 'Bookmakers',
                'db_table': '"betting_data"."bookmakers"',
                'managed': False,
            },
        ),
    ]
