# Generated by Django 4.2.22 on 2025-06-10 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('event_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'betting_data"."events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TwoUp',
            fields=[
                ('market_id', models.UUIDField()),
                ('market_name', models.TextField()),
                ('participant_id', models.UUIDField()),
                ('participant_name', models.TextField()),
                ('back_bookmaker', models.TextField()),
                ('back_odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lay_bookmaker', models.TextField()),
                ('lay_odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'betting_data"."two_up',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('link', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_uid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Supabase UID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserToolPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tool')},
            },
        ),
    ]
