# Generated by Django 4.2.22 on 2025-06-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
