# Generated by Django 4.2.22 on 2025-06-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_event_options_alter_event_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
